<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);1591</NoWarn>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<ContainerDevelopmentMode>Regular</ContainerDevelopmentMode>
		<EnableDockerSupport>false</EnableDockerSupport>
		<UserSecretsId>c3d50263-41f3-4245-9f69-80efbea80d7f</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.27" />
		<PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
		<PackageReference Include="MediatR" Version="14.1.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.27">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CondominioSaaS.Application\CondominioSaaS.Application.csproj" />
		<ProjectReference Include="..\CondominioSaaS.Configurations\CondominioSaaS.Configurations.csproj" />
		<ProjectReference Include="..\CondominioSaaS.Infrastructure\CondominioSaaS.Infrastructure.csproj" />
	</ItemGroup>

</Project>
